services:
  canalsecureapiapp:
    container_name: securecanalappcontainer
    build: .
    image: securecanalapp:v1
    ports:
      - 8080:80
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
