services:
  canalsecureapi:
    container_name: securecanalcontainer
    build: .
    image: securecanal:v1
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
